
services:

  onlinestoreCache:
    container_name: onlinestoreCache
    restart: always
    ports:
      - "6379:6379"

  onlinestoredb:
        container_name: onlinestoredb
        user: root
        ports:
            - "54581:1433"
        environment:
            MSSQL_SA_PASSWORD: "SwN12345678"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
            MSSQL_AGENT_ENABLED: "true"
        volumes:
           - type: volume
             source: db-data
             target: /var/opt/mssql/data
           - ./log/:/var/opt/mssql/log/


  onlinestore:
    container_name: onlineStoreApi
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      #- ASPNETCORE_HTTPS_PORT=5001
      - RedisConnection:Configuration=onlinestoreCache:6379
      - ConnectionStrings:DefaultConnection=Server=onlinestoredb;Database=Shopping.Api;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/onlinestore.pfx

    ports:
      - "5001:443"
      #- "5001:5001"

    
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https
    
    depends_on:
      - onlinestoredb
      - onlinestoreCache

    develop:
      watch:
        - action: rebuild
          path: ./OnlineStore
    
    restart: on-failure
    
volumes:
  db-data: